---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: site/content/artists
  label: Artists
  create: all
  match: "**/*"
- type: directory
  path: site/content/spotlight
  label: Spotlight
  create: all
  match: "**/*"
- type: directory
  path: site/content/issues
  label: Issues
  create: all
  match: "**/*"
- type: directory
  path: site/content/artwork
  label: Artwork
  create: all
  match: "**/*"
upload_dir: site/static/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: site/public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv/site"
  instant_preview_command: hugo server --renderToDisk --port 8080 --bind 0.0.0.0
version: 0.58.2
